name: Deploy to GitHub Pages
# REF: https://docs.astro.build/ja/guides/deploy/github/
# REF: https://blog.kimulaco.dev/article/microcms-webhook-to-github-actions/
on:
  push:
    branches: [main]

  repository_dispatch:
    types: [update_post]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout this repository using git
        uses: actions/checkout@v4

      - name: Install, build, and upload
        uses: withastro/action@v2
        with:
          node-version: 20
        env:
          PUBLIC_MICROCMS_API_URL: ${{ secrets.PUBLIC_MICROCMS_API_URL }}
          PUBLIC_MICROCMS_API_URL_2: ${{ secrets.PUBLIC_MICROCMS_API_URL_2 }}
          PUBLIC_MICROCMS_API_URL_3: ${{ secrets.PUBLIC_MICROCMS_API_URL_3 }}
          PUBLIC_MICROCMS_API_KEY: ${{ secrets.PUBLIC_MICROCMS_API_KEY }}
          PUBLIC_MICROCMS_API_KEY_2: ${{ secrets.PUBLIC_MICROCMS_API_KEY_2 }}
          PUBLIC_MICROCMS_API_KEY_3: ${{ secrets.PUBLIC_MICROCMS_API_KEY_3 }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
