name: Deploy to GitHub Pages
# REF: https://docs.astro.build/ja/guides/deploy/github/
on:
  push:
    branches: [main]

  repository_dispatch:
    types: [update_post]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUBLIC_MICROCMS_API_URL: ${{ secrets.PUBLIC_MICROCMS_API_URL }}
      PUBLIC_MICROCMS_API_URL_2: ${{ secrets.PUBLIC_MICROCMS_API_URL_2 }}
      PUBLIC_MICROCMS_API_URL_3: ${{ secrets.PUBLIC_MICROCMS_API_URL_3 }}
      PUBLIC_MICROCMS_API_KEY: ${{ secrets.PUBLIC_MICROCMS_API_KEY }}
      PUBLIC_MICROCMS_API_KEY_2: ${{ secrets.PUBLIC_MICROCMS_API_KEY_2 }}
      PUBLIC_MICROCMS_API_KEY_3: ${{ secrets.PUBLIC_MICROCMS_API_KEY_3 }}
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          corepack enable
          pnpm install

      - name: Build Astro project
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
