name: Deploy to GitHub Pages
# REF: https://docs.astro.build/ja/guides/deploy/github/
on:
  push:
    branches: [main]

  repository_dispatch:
    types: [update_post]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout this repository using git
        uses: actions/checkout@v4

      - name: Install, build, and upload
        uses: withastro/action@v1
        with:
          node-version: 20
        env:
          MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
